steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/bl0608/gcp-poc.git
        cd gcp-poc
        gsutil -m cp -r ./*.py gs://australia-southeast1-poc-co-f4015def-bucket/dags/

timeout: '1200s'
